apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
  namespace: janu-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: jahnavipullakura/jahnavi-wipro:springbootapp-latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: janu-namespace
spec:
  type: NodePort
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30083
